version: '3.8'

services:
  indexer-db:
    image: postgres
    container_name: postgres-indexer
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/indexer/postgres:/var/lib/postgresql/data
      - /etc/letsencrypt/live/${PROD_URL}/fullchain.pem:/var/lib/postgresql/server.crt:ro
      - /etc/letsencrypt/live/${PROD_URL}/privkey.pem:/var/lib/postgresql/server.key:ro
    command:
      - 'postgres'
      - '-c'
      - 'ssl=on'
      - '-c'
      - 'ssl_cert_file=/var/lib/postgresql/server.crt'
      - '-c'
      - 'ssl_key_file=/var/lib/postgresql/server.key'
      - '-c'
      - 'shared_buffers=8GB'
      - '-c'
      - 'effective_cache_size=24GB'
      - '-c'
      - 'maintenance_work_mem=2GB'
      - '-c'
      - 'work_mem=64MB'
      - '-c'
      - 'max_wal_size=16GB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'effective_io_concurrency=200'
      - '-c'
      - 'synchronous_commit=off'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  db-migration:
    build:
      context: ../
      dockerfile: Dockerfile.development
    container_name: db-migration
    environment:
      DB_HOST: indexer-db
    command: ['yarn', 'create:database']
    depends_on:
      indexer-db:
        condition: service_healthy

  graphql-app:
    build:
      context: ../
      dockerfile: Dockerfile.development
    container_name: kad-indexer-graphql
    environment:
      DB_HOST: indexer-db
    command: ['yarn', 'dev:graphql']
    ports:
      - '3001:3001'
    depends_on:
      db-migration:
        condition: service_completed_successfully

  streaming-app:
    build:
      context: ../
      dockerfile: Dockerfile.development
    container_name: kad-indexer-streaming
    environment:
      DB_HOST: index-db
      KADENA_GRAPHQL_API_URL: http://graphql-app
    command: ['yarn', 'dev:streaming']
    depends_on:
      graphql-app:
        condition: service_started
