FROM postgres:17

RUN apt-get update
RUN apt-get install -y libbz2-dev libpq-dev libyaml-dev curl git gcc libssl-dev libxml2-dev libperl-dev zlib1g-dev pkg-config meson ninja-build liblz4-dev openssh-client gettext-base ssh cron && rm -rf /var/lib/apt/lists/*

# install pgbackrest 2.56.0
RUN curl -L -o pgbackrest-2.56.0.tar.gz https://github.com/pgbackrest/pgbackrest/archive/refs/tags/release/2.56.0.tar.gz
RUN tar -xzf pgbackrest-2.56.0.tar.gz
RUN cd pgbackrest-release-2.56.0 && meson setup builddir && ninja -C builddir && ninja -C builddir install && hash -r

# Create folders for pgBackRest and adjust permissions
RUN mkdir -p /tmp/pgbackrest /var/log/pgbackrest && \
    chown postgres:postgres /tmp/pgbackrest /var/log/pgbackrest && \
    chmod 700 /tmp/pgbackrest /var/log/pgbackrest

# Add the pgbackrest configuration file
COPY pgbackrest.conf.generated /etc/pgbackrest.conf
RUN chown postgres:postgres /etc/pgbackrest.conf && \
    chmod 600 /etc/pgbackrest.conf

# Create the pgbackrest backup logs folder and adjust permissions
RUN mkdir -p /var/lib/postgresql/pgbackrest-logs && \
    chown postgres:postgres /var/lib/postgresql/pgbackrest-logs

# Create the .ssh folder and copy the SSH keys
RUN mkdir -p /var/lib/postgresql/.ssh
COPY id_ed25519 /var/lib/postgresql/.ssh/id_ed25519
COPY id_ed25519.pub /var/lib/postgresql/.ssh/id_ed25519.pub

# Adjust permissions for the SSH keys
RUN chown -R postgres:postgres /var/lib/postgresql/.ssh && \
    chmod 700 /var/lib/postgresql/.ssh && \
    chmod 600 /var/lib/postgresql/.ssh/id_ed25519 && \
    chmod 644 /var/lib/postgresql/.ssh/id_ed25519.pub

# Copy the custom initialization script
COPY script.sh.generated /script.sh
RUN chmod +x /script.sh

# Expose the default PostgreSQL port
EXPOSE 5432
EXPOSE 5433

# Default CMD to keep container alive and interactive
CMD ["bash"]