# Prometheus configuration file for Kadena Indexer monitoring
#
# This configuration file defines the Prometheus scraping settings for monitoring
# the Kadena Indexer application. Prometheus will collect metrics from the
# specified endpoints to provide observability into the indexer's performance.

global:
  scrape_interval: 15s # How frequently to scrape targets (every 15 seconds)

scrape_configs:
  - job_name: 'kadena-indexer' # Unique name for the monitoring job
    metrics_path: '/metrics' # Path to the metrics endpoint
    static_configs:
      - targets: ['host.docker.internal:3000'] # Docker host address and port of the metrics server
